# Generated by Django 5.2 on 2025-08-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='password',
            field=models.CharField(default='123456', max_length=128),
        ),
    ]
