# Generated by Django 5.2 on 2025-08-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0002_pharmacy_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='Admin123456', max_length=255),
        ),
    ]
