# Generated by Django 5.2 on 2025-08-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0003_adminuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocationrate',
            name='drop_city',
        ),
        migrations.RemoveField(
            model_name='deliverylocationrate',
            name='pickup_city',
        ),
        migrations.AddField(
            model_name='deliverylocationrate',
            name='max_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deliverylocationrate',
            name='min_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
