# Generated by Django 5.2 on 2025-08-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0004_remove_deliverylocationrate_drop_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryLocationRate',
        ),
    ]
