# Generated by Django 5.2 on 2025-08-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0006_deliverylocationrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryLocationRate',
        ),
    ]
