# Generated by Django 5.2 on 2025-08-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0007_delete_deliverylocationrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDistanceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
