# Generated by Django 5.2 on 2025-08-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0008_deliverydistancerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='pickup_city',
            field=models.CharField(default='Kitchener', max_length=100),
        ),
    ]
