# Generated by Django 5.2 on 2025-08-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0009_deliveryorder_pickup_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrderTracking',
        ),
    ]
