# Generated by Django 5.2 on 2025-08-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0010_delete_deliveryordertracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted by Driver'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('handover', 'Pharmacy Handover')], max_length=20)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='CanaDrop_Interface.deliveryorder')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
