# Generated by Django 5.2 on 2025-08-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0011_deliveryordertracking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryOrderTracking',
            new_name='OrderTracking',
        ),
    ]
