# Generated by Django 5.2 on 2025-08-26 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0012_rename_deliveryordertracking_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_entries', to='CanaDrop_Interface.driver'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_entries', to='CanaDrop_Interface.pharmacy'),
        ),
    ]
