# Generated by Django 5.2 on 2025-08-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0016_driver_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='password',
        ),
    ]
