# Generated by Django 5.2 on 2025-08-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0019_remove_driver_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='123456', max_length=128),
        ),
    ]
