# Generated by Django 5.2 on 2025-08-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0020_driver_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('inTransit', 'In Transit'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='step',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted by Driver'), ('picked_up', 'Picked Up'), ('inTransit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('handover', 'Pharmacy Handover')], max_length=20),
        ),
    ]
