# Generated by Django 5.2 on 2025-08-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0021_alter_deliveryorder_status_alter_ordertracking_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
