# Generated by Django 5.2 on 2025-08-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0022_invoice_stripe_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpaymenttracking',
            name='payment',
        ),
        migrations.DeleteModel(
            name='DriverPayment',
        ),
        migrations.DeleteModel(
            name='DriverPaymentTracking',
        ),
    ]
