# Generated by Django 5.2 on 2025-08-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0023_remove_driverpaymenttracking_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_deliveries', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('paid', 'Paid')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='CanaDrop_Interface.driver')),
            ],
        ),
    ]
