# Generated by Django 5.2 on 2025-08-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0024_driverinvoice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='canadrop_interface_adminuser',
        ),
        migrations.AlterModelTable(
            name='pharmacy',
            table='canadrop_interface_pharmacy',
        ),
    ]
