# Generated by Django 5.2 on 2025-08-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0025_alter_adminuser_table_alter_pharmacy_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driver',
            table='canadrop_interface_driver',
        ),
    ]
