# Generated by Django 5.2 on 2025-08-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0026_alter_driver_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliverydistancerate',
            table='canadrop_interface_deliverydistancerate',
        ),
    ]
