# Generated by Django 5.2 on 2025-08-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0027_alter_deliverydistancerate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryorder',
            table='canadrop_interface_deliveryorder',
        ),
    ]
