# Generated by Django 5.2 on 2025-08-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0028_alter_deliveryorder_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderimage',
            table='canadrop_interface_orderimage',
        ),
    ]
