# Generated by Django 5.2 on 2025-08-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0030_alter_invoice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driverinvoice',
            table='canadrop_interface_driverinvoice',
        ),
        migrations.AlterModelTable(
            name='ordertracking',
            table='canadrop_interface_ordertracking',
        ),
    ]
