# Generated by Django 5.2 on 2025-08-28 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0031_alter_driverinvoice_table_alter_ordertracking_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('account_creation', 'Account Creation Issue'), ('login_problem', 'Login / Authentication Problem'), ('password_reset', 'Password Reset Issue'), ('profile_update', 'Profile / Information Update Issue'), ('order_placement', 'Order Placement Issue'), ('order_cancellation', 'Order Cancellation Issue'), ('order_tracking', 'Order Tracking / Status Issue'), ('order_payment', 'Order Payment / Rate Issue'), ('pickup_issue', 'Pickup Issue by Driver'), ('delivery_delay', 'Delivery Delay'), ('delivery_incorrect', 'Incorrect Delivery / Item Issue'), ('driver_unavailable', 'Driver Unavailable / Assignment Issue'), ('invoice_generated', 'Invoice Generated Issue'), ('invoice_payment', 'Invoice Payment / Stripe Issue'), ('driver_invoice', 'Driver Invoice / Payment Issue'), ('technical_bug', 'Technical / App Bug'), ('cloud_storage', 'Cloud / Image Upload Issue'), ('notification', 'Notification / Alert Issue'), ('feedback', 'Feedback / Suggestion'), ('other', 'Other')], max_length=50)),
                ('other_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='CanaDrop_Interface.driver')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='CanaDrop_Interface.pharmacy')),
            ],
            options={
                'db_table': 'canadrop_interface_contactadmin',
                'ordering': ['-created_at'],
            },
        ),
    ]
