# Generated by Django 5.2 on 2025-12-26 20:48

import CanaDrop_Interface.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0032_contactadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyTrialOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('pharmacy_phone', models.CharField(max_length=20)),
                ('pharmacy_email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('store_hours', models.CharField(help_text='Example: Mon–Fri 9am–7pm', max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('pharmacist', 'Pharmacist')], max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('currently_offers_delivery', models.BooleanField(default=False)),
                ('estimated_deliveries_per_day', models.PositiveIntegerField()),
                ('preferred_delivery_type', models.CharField(choices=[('same_day', 'Same-day'), ('next_day', 'Next-day'), ('both', 'Both')], max_length=10)),
                ('same_day_cutoff_time', models.TimeField(blank=True, help_text='Required if same-day delivery is selected', null=True)),
                ('delivery_radius_km', models.PositiveIntegerField(help_text='Delivery radius in kilometers')),
                ('signature_required', models.BooleanField(default=True)),
                ('id_verification_required', models.BooleanField(default=False)),
                ('special_delivery_instructions', models.TextField(blank=True, null=True)),
                ('trial_start_date', models.DateField()),
                ('trial_duration_days', models.PositiveIntegerField(default=7)),
                ('agreed_delivery_fee', models.DecimalField(decimal_places=2, help_text='Per delivery fee during trial', max_digits=6)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Converted to Active'), ('inactive', 'Inactive')], default='trial', max_length=10)),
            ],
            options={
                'verbose_name': 'Pharmacy Trial Onboarding',
                'verbose_name_plural': 'Pharmacy Trial Onboardings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_name',
            field=models.CharField(default='John Doe', max_length=150),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='id_verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='signature_ack_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='signature_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='identity_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='business_hours',
            field=models.JSONField(default=CanaDrop_Interface.models.default_business_hours),
        ),
        migrations.CreateModel(
            name='CCPointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_points', to='CanaDrop_Interface.driver')),
                ('pharmacy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_points', to='CanaDrop_Interface.pharmacy')),
            ],
            options={
                'db_table': 'canadrop_interface_ccpointsaccount',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('driver__isnull', True), ('pharmacy__isnull', False)), models.Q(('driver__isnull', False), ('pharmacy__isnull', True)), _connector='OR'), name='ccpoints_single_entity_only')],
            },
        ),
    ]
