# Generated by Django 4.2.23 on 2026-01-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0034_paymentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('pharmacy_phone', models.CharField(max_length=20)),
                ('pharmacy_email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('store_hours', models.CharField(help_text='Example: Mon–Fri 9am–7pm', max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('pharmacist', 'Pharmacist')], max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('currently_offers_delivery', models.BooleanField(default=False)),
                ('estimated_deliveries_per_day', models.PositiveIntegerField()),
                ('preferred_delivery_type', models.CharField(choices=[('same_day', 'Same-day'), ('next_day', 'Next-day'), ('both', 'Both')], max_length=10)),
                ('delivery_radius_km', models.PositiveIntegerField(help_text='Delivery radius in kilometers')),
                ('signature_required', models.BooleanField(default=True)),
                ('id_verification_required', models.BooleanField(default=False)),
                ('special_delivery_instructions', models.TextField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for analytics and tracking', null=True)),
            ],
            options={
                'verbose_name': 'Pharmacy Information',
                'verbose_name_plural': 'Pharmacy Information',
                'db_table': 'canadrop_interface_pharmacyinfo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PharmacyTrialOnboarding',
        ),
 
    ]

