# Generated by Django 4.2.23 on 2026-01-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0035_pharmacyinfo_delete_pharmacytrialonboarding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverinvoice',
            name='payment_reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentinformation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('payment_type',), name='unique_active_payment_type'),
        ),
    ]
