# Generated by Django 4.2.23 on 2026-01-11 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0036_driverinvoice_payment_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverinvoice',
            name='payment_reference_id',
        ),
    ]
