# Generated by Django 4.2.23 on 2026-01-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0038_driverinvoice_payment_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='driver_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
