# Generated by Django 4.2.23 on 2026-01-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0039_deliveryorder_driver_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='auto_insurance_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='right_to_work_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_ownership_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
