# Generated by Django 4.2.23 on 2026-01-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0040_driver_auto_insurance_url_driver_driver_license_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_contract',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='privacy_laws_agreement',
            field=models.URLField(blank=True, null=True),
        ),
    ]
