# Generated by Django 4.2.23 on 2026-01-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CanaDrop_Interface', '0041_driver_driver_contract_driver_privacy_laws_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='authorized_to_store_banking_details',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_institution_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_transit_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
