from django.urls import path
from . import views  # make sure the import works

urlpatterns = [
    path('pharmacyLogin/', views.pharmacyLoginView, name='PharmacyLoginPage'),  
    path('pharmacyDashboard/', views.pharmacyDashboardView, name="PharmacyDashboardPage"),
    path('pharmacyOrders/', views.pharmacyOrdersView, name="PharmacyOrdersPage"),
    path('pharmacyInvoices/', views.pharmacyInvoicesView, name="PharmacyInvoicesPage"),
    path('api/pharmacy/login/', views.pharmacy_login_api, name='pharmacy-login-api'),
    path('api/createDeliveryOrder/', views.create_delivery_order, name='create_delivery_order'),
    path("api/get-delivery-rate/", views.get_delivery_rate, name="get_delivery_rate"),
    path("pharmacy/<int:pharmacy_id>/", views.get_pharmacy_details, name="get_pharmacy_details"),
    path("pharmacy/<int:pharmacy_id>/orders/", views.get_pharmacy_orders, name="get_pharmacy_orders"),
    path('api/pharmacy/<int:pharmacy_id>/orders/', views.pharmacy_orders_api, name='pharmacy_orders_api'),
    path('api/upload-handover-image/', views.upload_handover_image_api, name='upload_handover_image'),
    path('pharmacyForgotPassword/', views.pharmacyForgotPasswordView, name="PharmacyForgotPasswordPage"),
    path('api/auth/register-pharmacy/', views.register_pharmacy, name='register_pharmacy'),
    path('pharmacyRegister/', views.pharmacyRegisterView, name="PharmacyRegisterPage"),
    path('pharmacyProfile/', views.pharmacyProfileView, name="PharmacyProfilePage"),
    path("api/getPharmacyDetails/<int:pharmacy_id>/", views.get_pharmacy_details, name="get_pharmacy_details"),
    path("api/changeExistingPassword/", views.change_existing_password, name="change_existing_password"),
    path("api/editPharmacyProfile/", views.edit_pharmacy_profile, name="edit_pharmacy_profile"),
    path('api/pharmacy-onboarding/', views.pharmacy_onboarding_api, name='pharmacy_onboarding_api'),
    path('pharmacyTrial/', views.pharmacyTrialOnboarding, name='PharmacyTrialOnboardingPage'),  
    path('pharmacyCCPoints/', views.pharmacyCCPointsView, name='PharmacyCCPointsPage'), 
    path('api/pharmacy/<int:pharmacy_id>/cc-points/', views.get_pharmacy_cc_points, name='pharmacy_cc_points'),


    path('driverLogin/', views.driverLoginView, name='DriverLoginPage'),  
    path('api/driver/login/', views.driver_login, name='driver_login'),
    path('driverDashboard/', views.driverDashboardView, name="DriverDashboardPage"),
    path("api/orders/pending/", views.get_pending_orders, name="get_pending_orders"),
    path("api/orders/assign-driver/", views.assign_driver, name="assign_driver"),
    path("api/driver/details/", views.get_driver_details, name="get_driver_details"),
    path('driverAcceptedDeliveries/', views.driverAcceptedDeliveriesView, name="DriverAcceptedDeliveriesPage"),
    path("api/driver-orders/", views.driver_accepted_orders, name="driver_accepted_orders"),
    path("api/driver-pickup-proof/", views.driver_pickup_proof, name="driver_pickup_proof"),
    path("api/driver-delivery-proof/", views.driver_delivery_proof, name="driver_delivery_proof"),
    path("api/generate-weekly-invoices/", views.generate_weekly_invoices, name="generate_weekly_invoices"),
    path('api/create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('webhooks/stripe/', views.stripe_webhook, name='stripe_webhook'),
    path('api/payment-status/', views.get_payment_status, name='payment_status'),
    path('driverFinances/', views.driverFinancesView, name="DriverFinancesPage"),
    path("api/driver/invoices/weeks/", views.driver_invoice_weeks, name="driver_invoice_weeks"),
    path('driverForgotPassword/', views.driverForgotPasswordView, name="driverForgotPasswordPage"),
    path('driverRegister/', views.driverRegisterView, name="driverRegisterPage"),
    path('api/driver/register/', views.register_driver, name='register_driver'),
    path("api/driver/optimize-route/", views.optimize_route_api, name="optimize_route_api"),
    path('driverIdentity/', views.driverIdentityView, name='DriverIdentityPage'),
    path("api/driver/upload-identity-image/", views.upload_driver_identity_image, name="upload-driver-identity-image"),
    path('api/upload-signature-acknowledgement/', views.upload_signature_acknowledgement, name='upload-signature-acknowledgement'),
    path('api/verify-customer-id/', views.verify_customer_id, name='verify-customer-id'),
    path('driverCCPoints/', views.driverCCPointsView, name='DriverCCPointsPage'), 
    path("api/driver/<int:driver_id>/cc-points/", views.get_driver_cc_points, name="driver_cc_points"),

    path('contactAdmin/', views.contactAdminView, name='contactAdminPage'), 
    path('api/contact-admin/', views.contact_admin_api, name='contact_admin_api'),
    path('adminLogin/', views.adminLoginView, name='AdminLoginPage'),  
    path("api/admin/login/", views.admin_login, name="admin_login"),
    path('adminDashboard/', views.adminDashboardView, name="AdminDashboardPage"),
    path('adminOrders/', views.adminOrdersView, name="AdminOrdersPage"),
    path('adminPharmacies/', views.adminPharmaciesView, name="AdminPharmaciesPage"),
    path('adminInvoices/', views.adminInvoicesView, name="AdminInvoicesPage"),
    path('adminSupport/', views.adminSupportView, name="AdminSupportPage"),
    path('adminDrivers/', views.adminDriversView, name="AdminDriversPage"),
    path("api/adminDashboardStats/", views.admin_dashboard_stats, name="admin_dashboard_stats"),
    path("api/recentActivityFeed/", views.recent_activity_feed, name="recent_activity_feed"),
    path("api/orderTrackingOverview/", views.order_tracking_overview, name="order_tracking_overview"),
    path("api/adminAlerts/", views.admin_alerts, name="admin_alerts"),
    path('api/adminOrderList/', views.admin_order_list, name='admin_order_list'),
    path("api/deliveryRates/", views.delivery_rates_list, name="delivery_rates_list"),
    path("api/editOrder/<int:order_id>/", views.edit_order, name="edit_order"),
    path("api/orders/<int:order_id>/cancel/", views.cancel_order, name="cancel_order"),
    path("api/deliveryRates/add/", views.add_delivery_rate, name="add_delivery_rate"),
    path("api/deliveryRates/<int:rate_id>/edit/", views.edit_delivery_rate, name="edit_delivery_rate"),
    path("api/deliveryRates/<int:rate_id>/delete/", views.delete_delivery_rate, name="delete_delivery_rate"),
    path("api/pharmacy/details/", views.get_pharmacy_details_admin, name="AdminPharmacyDetailsAll"),
    path("api/pharmacy/details/<int:pharmacy_id>/", views.get_pharmacy_details_admin, name="AdminPharmacyDetails"),
    path("pharmacy/add/", views.add_pharmacy, name="AdminAddPharmacy"),
    path("pharmacy/edit/<int:pharmacy_id>/", views.edit_pharmacy, name="AdminEditPharmacy"),
    path("pharmacy/toggle-status/<int:pharmacy_id>/", views.toggle_pharmacy_status, name="AdminTogglePharmacyStatus"),
    path("pharmacy/reset-password/<int:pharmacy_id>/", views.reset_pharmacy_password, name = "AdminResetCredentials"),
    path("api/admin/driver/details/", views.get_driver_details_admin, name="AdminDriverDetailsAll"),
    path("api/admin/driver/details/<int:driver_id>/", views.get_driver_details_admin, name="AdminDriverDetails"),
    path("api/driver/add/", views.add_driver, name="AdminAddDriver"),
    path("api/driver/edit/<int:driver_id>/", views.edit_driver, name="AdminEditDriver"),
    path("api/driver/toggle-status/<int:driver_id>/", views.toggle_driver_status, name="AdminToggleDriverStatus"),
    path("api/driver/reset-password/<int:driver_id>/", views.reset_driver_password, name="AdminResetDriverPassword"),
    path("api/admin/invoices/all/", views.get_all_pharmacy_invoices, name="AdminFetchAllPharmacyInvoices"),
    path("api/admin/driver-invoices/all/", views.get_all_driver_invoices, name="AdminFetchAllDriverInvoices"),
    path("api/admin/payment-alerts/", views.get_payment_alerts, name="AdminFetchAllPaymentAlerts"),
    path("api/admin/financials/month/", views.get_monthly_financials, name="AdminMonthlyFinancials"),
    path("api/admin/support/tickets/", views.get_contact_ticket_details, name="AdminSupportTicketDetails"),
    path("api/admin/support/tickets/<int:ticket_id>/", views.get_contact_ticket_details, name="AdminSupportTicketDetail"),
    path("api/admin/support/tickets/<int:ticket_id>/status/",views.update_ticket_status,name="AdminUpdateTicketStatus"),
    path("api/admin/support/tickets/<int:ticket_id>/respond/", views.add_admin_response, name="AdminAddTicketResponse"),
    path("api/admin/support/tickets/metrics/", views.get_ticket_status_metrics, name="AdminSupportTicketMetrics"),



    path('', views.landingView, name='landingPage'),

    path('api/auth/send-otp/', views.send_otp, name='send_otp'),
    path('api/auth/verify-otp/', views.verify_otp, name='verify_otp'),
    path('api/auth/change-password/', views.change_password, name='change_password'),
    path('api/driver/change-password/', views.change_password_driver, name='change_password_driver'),


    

]
